### ISSUE TITLE
Allow for $home overrides in ohmyzsh::params

### ISSUE THREAD

**Issue by mikedevita** [zanloy/puppet-ohmyzsh#7]
Currently none of the params are exposed so you can't override them with an ENC like foreman. I propose to extend this module to allow `$home` to be overridden, you can do this by exposing the $home as a class parameter in the `manifests/params.pp`.

Something like this should suffice for now:

**manifests/init.pp**
```puppet
# View README.md for full documentation.
#
# === Authors
#
# Leon Brocard <acme@astray.com>
# Zan Loy <zan.loy@gmail.com>
#
# === Copyright
#
# Copyright 2014
#
class ohmyzsh (
  $home = $::ohmyzsh::params::homedir
) inherits ::ohmyzsh::params {}
```

**manifests/params.pp**

```puppet
# Parameters class for ohmyzsh
class ohmyzsh::params (
  $homedir = '/home'
) {
  case $::osfamily {
    'Redhat': {
      $zsh = '/bin/zsh'
    }
    default: {
      $zsh = '/usr/bin/zsh'
    }
  }

  $home = $homedir

}
```

I will submit a PR for this if you like (although I am still fairly new to puppet), I also was thinking about creating a wrapper for this module so you can use an ENC via hiera/yaml to define something like the following:

```yaml
users:
  root:
    set_sh: true
    disable_auto_update: true
    homedir: /root
    theme: 'robyrussell'  
  mike:
    set_sh: true
    disable_auto_update: true
    homedir: /mnt/home/mike
    theme: 'robyrussell'
    plugins:
      - git
      - github
```
